/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-08-29 09:41:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import com.wild_tour.connection.Connector;
import com.wild_tour.dto.User;

public final class myTrip_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.wild_tour.connection.Connector");
    _jspx_imports_classes.add("com.wild_tour.dto.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");
    if (user == null) {
        response.sendRedirect("login.jsp");
        return;
    }

    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>My Trips</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background: #eef1f4;\r\n");
      out.write("            font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            max-width: 1000px;\r\n");
      out.write("            margin: 50px auto;\r\n");
      out.write("        }\r\n");
      out.write("        .back {\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .trip-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0 6px 12px rgba(0,0,0,0.1);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .trip-card img {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 140px;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .trip-info {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("        }\r\n");
      out.write("        .trip-info h3 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            color: #2e7d32;\r\n");
      out.write("        }\r\n");
      out.write("        .trip-info p {\r\n");
      out.write("            margin: 5px 0;\r\n");
      out.write("        }\r\n");
      out.write("        .cancel-btn {\r\n");
      out.write("            background-color: #dc3545;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 8px 14px;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .cancel-btn:hover {\r\n");
      out.write("            background-color: #c82333;\r\n");
      out.write("        }\r\n");
      out.write("        .status-badge {\r\n");
      out.write("            padding: 4px 10px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 0.9em;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .status-confirmed {\r\n");
      out.write("            background-color: #d4edda;\r\n");
      out.write("            color: #155724;\r\n");
      out.write("        }\r\n");
      out.write("        .status-cancelled {\r\n");
      out.write("            background-color: #f8d7da;\r\n");
      out.write("            color: #721c24;\r\n");
      out.write("        }\r\n");
      out.write("        .status-completed {\r\n");
      out.write("            background-color: #d1ecf1;\r\n");
      out.write("            color: #0c5460;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h2>My Booked Trips</h2>\r\n");
      out.write("    <div class=\"back\">\r\n");
      out.write("        <a href=\"dashboard.jsp\" class=\"btn btn-primary\">Back</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");

    try {
        con = Connector.requestConnection();
        String sql = "SELECT * FROM booking WHERE user_id = ? ORDER BY booked_date DESC";
        ps = con.prepareStatement(sql);
        ps.setInt(1, user.getUserId());
        rs = ps.executeQuery();

        boolean hasTrips = false;

        while (rs.next()) {
            hasTrips = true;
            int bookingId = rs.getInt("booking_id");
            String itemType = rs.getString("item_type");
            String itemName = rs.getString("item_name");
            String imageUrl = rs.getString("item_image");
            int numPersons = rs.getInt("num_persons");
            double totalPrice = rs.getDouble("total_price");
            String paymentMode = rs.getString("payment_mode");
            String status = rs.getString("status").toLowerCase();

            String displayStatus = status;
            String statusClass = "status-confirmed";

            if ("booked".equals(status)) {
                displayStatus = "confirmed";
            } else if ("cancelled".equals(status)) {
                statusClass = "status-cancelled";
            } else if ("completed".equals(status)) {
                statusClass = "status-completed";
            }

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"trip-card\">\r\n");
      out.write("        <img src=\"");
      out.print( imageUrl );
      out.write("\" alt=\"Trip Image\" />\r\n");
      out.write("        <div class=\"trip-info\">\r\n");
      out.write("            <h3>");
      out.print( itemName );
      out.write(' ');
      out.write('(');
      out.print( itemType );
      out.write(")</h3>\r\n");
      out.write("            <p><strong>Number of Persons:</strong> ");
      out.print( numPersons );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("            ");
 if ("Safari".equalsIgnoreCase(itemType) || "Guide".equalsIgnoreCase(itemType)) { 
      out.write("\r\n");
      out.write("                <p><strong>Booked Date:</strong> ");
      out.print( rs.getDate("booking_date") );
      out.write("</p>\r\n");
      out.write("            ");
 } else if ("Stay".equalsIgnoreCase(itemType) || "Package".equalsIgnoreCase(itemType)) { 
      out.write("\r\n");
      out.write("                <p><strong>From:</strong> ");
      out.print( rs.getDate("from_date") );
      out.write("</p>\r\n");
      out.write("                <p><strong>To:</strong> ");
      out.print( rs.getDate("to_date") );
      out.write("</p>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <p><strong>Total Price:</strong> ₹ ");
      out.print( totalPrice );
      out.write("</p>\r\n");
      out.write("            <p><strong>Payment Mode:</strong> ");
      out.print( paymentMode );
      out.write("</p>\r\n");
      out.write("            <p><strong>Status:</strong>\r\n");
      out.write("                <span class=\"status-badge ");
      out.print( statusClass );
      out.write("\">\r\n");
      out.write("                    ");
      out.print( displayStatus.substring(0, 1).toUpperCase() + displayStatus.substring(1) );
      out.write("\r\n");
      out.write("                </span>\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            ");
 if (!"cancelled".equals(status) && !"completed".equals(status)) { 
      out.write("\r\n");
      out.write("                <form action=\"CancelBookingServlet\" method=\"post\" style=\"margin-top:10px;\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"booking_id\" value=\"");
      out.print( bookingId );
      out.write("\">\r\n");
      out.write("                    <button type=\"submit\" class=\"cancel-btn\">Cancel Booking</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");

        }

        if (!hasTrips) {

      out.write("\r\n");
      out.write("    <p>You have not booked any trips yet.</p>\r\n");

        }

    } catch (Exception e) {
        e.printStackTrace();

      out.write("\r\n");
      out.write("    <p style=\"color: red;\">Failed to load trip data. Please try again later.</p>\r\n");

    } finally {
        if (rs != null) try { rs.close(); } catch (Exception ignored) {}
        if (ps != null) try { ps.close(); } catch (Exception ignored) {}
        if (con != null) try { con.close(); } catch (Exception ignored) {}
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
