/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-08-29 09:42:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.wild_tour.dto.User;

public final class photography_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1756455307733L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1756455307781L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.wild_tour.dto.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Kabini Wildlife Photography</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Arial', sans-serif;\r\n");
      out.write("            background-color: #f4f4f4;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Hero Section */\r\n");
      out.write("        .hero-section {\r\n");
      out.write("            background-image: url('https://thrillingtravel.in/wp-content/uploads/2021/01/Zone-B-Kabini.jpg');\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            height: 60vh;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 80px 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-section h1 {\r\n");
      out.write("            font-size: 3rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-section p {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* Gallery Section */\r\n");
      out.write("        .gallery-container {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("            margin: 50px 0;\r\n");
      out.write("            padding: 0 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .gallery-item {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .gallery-item img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            transition: transform 0.3s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .gallery-item:hover img {\r\n");
      out.write("            transform: scale(1.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .gallery-item .caption {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 10px;\r\n");
      out.write("            left: 10px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            background-color: rgba(0, 0, 0, 0.6);\r\n");
      out.write("            padding: 5px 10px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write(".activity-card {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-wrap: wrap;\r\n");
      out.write("  background-color: #f4f9f4;\r\n");
      out.write("  border-radius: 12px;\r\n");
      out.write("  box-shadow: 0 4px 10px rgba(0,0,0,0.1);\r\n");
      out.write("  margin: 20px 0;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".activity-image img {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  max-width: 400px;\r\n");
      out.write("  object-fit: cover;\r\n");
      out.write("  padding-top: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".activity-content {\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  flex: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".activity-content h2 {\r\n");
      out.write("  font-size: 28px;\r\n");
      out.write("  color: #2e5e4e;\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".activity-content p {\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  color: #444;\r\n");
      out.write("  margin: 8px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".activity-features {\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".activity-features li {\r\n");
      out.write("  margin-bottom: 6px;\r\n");
      out.write("  font-size: 15px;\r\n");
      out.write("  color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".activity-details {\r\n");
      out.write("  background-color: #e0f2e9;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("  border-radius: 8px;\r\n");
      out.write("  margin: 15px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("    background-color: #343a40;\r\n");
      out.write("    width:100%;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 20px 0;\r\n");
      out.write("    margin-top: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("       ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");
    boolean isLoggedIn = (user != null);
    boolean isAdmin = isLoggedIn && user.getUserId() == 1;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Wildlife Header</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-mQ93xN6+zTQ4Zw6KtI2pHRY4OaCEk36zI4eYtvH6uwGbFk77J3bWhNRiKtCkVpWZ\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background-color: #f4f8f4;\r\n");
      out.write("            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.08);\r\n");
      out.write("            font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("            padding:15px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #2e7d32 !important;\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-nav .nav-link {\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-right: 15px;\r\n");
      out.write("            transition: color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-nav .nav-link:hover {\r\n");
      out.write("            color: #2e7d32;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown-menu {\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown-item:hover {\r\n");
      out.write("            background-color: #eaf5ea;\r\n");
      out.write("            color: #2e7d32;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-toggler {\r\n");
      out.write("            border-color: rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-toggler-icon {\r\n");
      out.write("            background-image: url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='%232e7d32' viewBox='0 0 30 30'%3e%3cpath stroke='rgba%280, 0, 0, 0.5%29' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e\");\r\n");
      out.write("        }\r\n");
      out.write("        .profile-dropdown {\r\n");
      out.write("    margin-left: 10px; \r\n");
      out.write("}\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.print( isLoggedIn ? "dashboard.jsp" : "Home.jsp" );
      out.write("\">\r\n");
      out.write("            <img src=\"https://tse4.mm.bing.net/th?id=OIP.vNrNrjSGanab468Bks6zNAAAAA&pid=Api&P=0&h=180\" alt=\"Wildlife Logo\" width=\"50\">\r\n");
      out.write("            Wildlife Tourism\r\n");
      out.write("        </a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print( isLoggedIn ? "dashboard.jsp" : "Home.jsp" );
      out.write("\">Home</a>\r\n");
      out.write("                </li>\r\n");
      out.write("               \r\n");
      out.write("\r\n");
      out.write("                ");
 if (!isLoggedIn) { 
      out.write("\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"login.jsp\">Login</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"signup.jsp\">Register</a></li>\r\n");
      out.write("                ");
 } else if (isAdmin) { 
      out.write("\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"adminDashboard.jsp\">Dashboard</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"trip_management.jsp\">Booked Trips</a></li>\r\n");
      out.write("                <li class=\"nav-item dropdown\">\r\n");
      out.write("    <a class=\"nav-link dropdown-toggle d-flex align-items-center\" href=\"#\" id=\"navbarProfileDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("        <i class=\"fa-solid fa-user-circle me-2\" style=\"font-size: 24px;\"></i>\r\n");
      out.write("        ");
      out.print( user.getUser_name() );
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("    <ul class=\"dropdown-menu profile-dropdown\" aria-labelledby=\"navbarProfileDropdown\">\r\n");
      out.write("        <li><a class=\"dropdown-item\" href=\"profile.jsp\">My Profile</a></li>\r\n");
      out.write("        <li><a class=\"dropdown-item\" href=\"logout.jsp\">Logout</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</li>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("            <li><a class=\"nav-link\" href=\"about.jsp\">About</a></li>\r\n");
      out.write("                \r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                            Our Activities\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"safari.jsp\">Wildlife Safaris</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"photography.jsp\">Wildlife Photography</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"wildlifeSighting.jsp\">Wildlife Sighting</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                            Tourism\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"package.jsp\">Tourism Packages</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"stay.jsp\">Accommodations</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"guide.jsp\">Guide Service</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a class=\"nav-link\" href=\"myTrip.jsp\">MyTrips</a></li>\r\n");
      out.write("                    <a class=\"nav-link\" href=\"contact.jsp\">Contact</a>\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                   <li class=\"nav-item dropdown\">\r\n");
      out.write("    <a class=\"nav-link dropdown-toggle d-flex align-items-center\" href=\"#\" id=\"navbarProfileDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("        <i class=\"fa-solid fa-user-circle me-2\" style=\"font-size: 24px;\"></i>\r\n");
      out.write("        ");
      out.print( user.getUser_name() );
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("    <ul class=\"dropdown-menu profile-dropdown\" aria-labelledby=\"navbarProfileDropdown\">\r\n");
      out.write("        <li><a class=\"dropdown-item\" href=\"profile.jsp\">My Profile</a></li>\r\n");
      out.write("        <li><a class=\"dropdown-item\" href=\"logout.jsp\">Logout</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</li>\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                    \r\n");
      out.write("        \r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-VRjE7nt98CkQnZzuw4nlPXf5ph2OydK6JZgZNUcQZDzA6BpAGjF2b7rE3L+dyO9g\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- Hero Section -->\r\n");
      out.write("    <section class=\"hero-section\" id=\"hero\">\r\n");
      out.write("        <h1>Discover the Beauty of Kabini</h1>\r\n");
      out.write("        <p>Explore stunning wildlife photography and immerse yourself in the serene landscapes of Kabini.</p>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Gallery Section -->\r\n");
      out.write("    <section id=\"gallery\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h2 class=\"text-center my-5\">Wildlife Photography</h2>\r\n");
      out.write("            <div class=\"gallery-container\">\r\n");
      out.write("                <!-- Gallery Item 1 -->\r\n");
      out.write("                <div class=\"gallery-item\">\r\n");
      out.write("                 <a href=\"blackpanther.jsp\">\r\n");
      out.write("                    <img src=\"https://mymodernmet.com/wp/wp-content/uploads/2020/07/black-panther-photos-shaaz-jung-2.jpeg\"\r\n");
      out.write("                        alt=\"Tiger\">\r\n");
      out.write("             \r\n");
      out.write("                    <div class=\"caption\">Roaming Black Panther</div>\r\n");
      out.write("</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Gallery Item 2 -->\r\n");
      out.write("                <div class=\"gallery-item\" >\r\n");
      out.write("                 <a href=\"elephant.jsp\">\r\n");
      out.write("                    <img src=\"https://www.theoutbackexperience.in/wp-content/uploads/2016/08/12_Elephant_Kabini-Gallery.jpg\"\r\n");
      out.write("                        alt=\"Elephant\">\r\n");
      out.write("                    <div class=\"caption\">Graceful Elephant</div></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Gallery Item 3 -->\r\n");
      out.write("                <div class=\"gallery-item\">\r\n");
      out.write("                 <a href=\"deer.jsp\">\r\n");
      out.write("                    <img src=\"https://redearth.in/blog/wp-content/uploads/2021/12/chital-kabini-.jpg\"\r\n");
      out.write("                        alt=\"Deer\">\r\n");
      out.write("                    <div class=\"caption\">Elegant Deer</div></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Gallery Item 4 -->\r\n");
      out.write("                <div class=\"gallery-item\" >\r\n");
      out.write("                 <a href=\"leopard.jsp\">\r\n");
      out.write("                    <img src=\"https://bigcatsindia.com/wp-content/uploads/2019/09/Indian-Leopard-Kabini-Wildlife.jpg\"\r\n");
      out.write("                        alt=\"Leopard\">\r\n");
      out.write("                    <div class=\"caption\">Leopard in Action</div></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"activity-card\">\r\n");
      out.write("  <div class=\"activity-image\">\r\n");
      out.write("    <img src=\"https://media.istockphoto.com/id/626056254/photo/clumsy-nature-photographer-dont-find-the-kingfisher-on-the-lens.jpg?s=612x612&w=0&k=20&c=USWn0BxiBMn3BDBdJJPp7DSEyvESXXQqg535lx0K0Cc=\" alt=\"Wildlife Photography\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"activity-content\">\r\n");
      out.write("    <h2>Wildlife Photography Information</h2>\r\n");
      out.write("    <p>Capture the untamed beauty of nature through your lens! Join our guided photo safaris to shoot stunning wildlife, rare birds, and breathtaking landscapes.</p>\r\n");
      out.write("    \r\n");
      out.write("    <ul class=\"activity-features\">\r\n");
      out.write("      <li>📷 Guided photo tours with experts</li>\r\n");
      out.write("      <li>🌄 Best zones during golden hours</li>\r\n");
      out.write("      <li>🦜 Birdwatching & animal tracking</li>\r\n");
      out.write("      <li>📚 Photography tips from professionals</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"activity-details\">\r\n");
      out.write("      <p><strong>Timings:</strong> 6:00 AM – 9:00 AM & 4:00 PM – 6:30 PM</p>\r\n");
      out.write("      <p><strong>Ideal For:</strong> Photographers, Nature Enthusiasts, Birdwatchers</p>\r\n");
      out.write("      <p><strong>Pro Tip:</strong> Carry a zoom lens (200mm+), wear earthy tones, and stay patient!</p>\r\n");
      out.write("    </div>\r\n");
      out.write("<div class=\"contact-details\">\r\n");
      out.write("  <p><strong>📞 For more details contact : +91 80456 78901</strong></p>\r\n");
      out.write("  \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Footer</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("    .footer {\r\n");
      out.write("        background-color: #0C2340;\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 60px 0;\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("    .footer a {\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: 400;\r\n");
      out.write("    }\r\n");
      out.write("    .footer a:hover {\r\n");
      out.write("        color: #ccc;\r\n");
      out.write("    }\r\n");
      out.write("    .social-icons {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        gap: 12px;\r\n");
      out.write("        margin-top: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    .social-icons a {\r\n");
      out.write("        width: 40px;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        color: white;\r\n");
      out.write("        transition: background 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("    .social-icons a:hover {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.4);\r\n");
      out.write("    }\r\n");
      out.write("    .gallery img {\r\n");
      out.write("        width: 70px;\r\n");
      out.write("        height: 70px;\r\n");
      out.write("        object-fit: cover;\r\n");
      out.write("        margin: 4px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .footer h5, .footer h4 {\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .contact-info p {\r\n");
      out.write("        margin: 8px 0;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer class=\"footer text-white\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row gy-4\">\r\n");
      out.write("            <!-- Logo & Description -->\r\n");
      out.write("            <div class=\"col-md-3 pe-4\">\r\n");
      out.write("                <div class=\"d-flex align-items-center mb-3\">\r\n");
      out.write("                    <img src=\"https://tse4.mm.bing.net/th?id=OIP.vNrNrjSGanab468Bks6zNAAAAA&pid=Api&P=0&h=180\" alt=\"Logo\" width=\"50\" class=\"me-2\">\r\n");
      out.write("                    <h4 class=\"mb-0\">WildLife Tourism</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p>Wildlife tourism offers travelers the unique opportunity to explore natural habitats, observe wild animals in their environment, and support conservation efforts while enjoying unforgettable adventures.</p>\r\n");
      out.write("                <div class=\"social-icons\">\r\n");
      out.write("                    <a href=\"#\"><i class=\"fa-brands fa-facebook-f\"></i></a>\r\n");
      out.write("                    <a href=\"#\"><i class=\"fa-brands fa-instagram\"></i></a>\r\n");
      out.write("                    <a href=\"#\"><i class=\"fa-brands fa-pinterest\"></i></a>\r\n");
      out.write("                    <a href=\"#\"><i class=\"fa-brands fa-twitter\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Links -->\r\n");
      out.write("            <!-- Links -->\r\n");
      out.write("<div class=\"col-md-3\">\r\n");
      out.write("    <h5 class=\"ms-5\">Links</h5>\r\n");
      out.write("    <div class=\"d-flex flex-column ms-5\">\r\n");
      out.write("        <a href=\"about.jsp\" class=\"mb-2\">About Us</a>\r\n");
      out.write("        <a href=\"photography.jsp\" class=\"mb-2\">Our Gallery</a>\r\n");
      out.write("        <a href=\"safari.jsp\" class=\"mb-2\">Safari</a>\r\n");
      out.write("        <a href=\"stay.jsp\" class=\"mb-2\">Accommodation</a>\r\n");
      out.write("        <a href=\"packages.jsp\" class=\"mb-2\">Wildlife Packages</a>\r\n");
      out.write("        <a href=\"guide.jsp\" class=\"mb-2\">Guide Service</a>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            <!-- Contact Info -->\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <h5>Contact</h5>\r\n");
      out.write("                <div class=\"contact-info\">\r\n");
      out.write("                    <p><i class=\"fas fa-phone me-2\"></i>666-888-0000</p>\r\n");
      out.write("                    <p><i class=\"fas fa-envelope me-2\"></i>needhelp@company.com</p>\r\n");
      out.write("                    <p><i class=\"fas fa-map-marker-alt me-2\"></i>66 Brooklyn Golden Street Line, Bangalore</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Gallery -->\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <h5>Gallery</h5>\r\n");
      out.write("                <div class=\"gallery d-flex flex-wrap\">\r\n");
      out.write("                    <img src=\"https://images.pexels.com/photos/3777200/pexels-photo-3777200.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500\" alt=\"img1\">\r\n");
      out.write("                    <img src=\"https://t4.ftcdn.net/jpg/02/75/68/23/360_F_275682379_DGTncKA0ydnvu2epbLmWVhsFGPrQ7uwA.jpg\" alt=\"img2\">\r\n");
      out.write("                    <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoeDUQNwoG1LMyx32vZ2uwhXERU0XhvWsOJw&s\" alt=\"img3\">\r\n");
      out.write("                    <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSbl9sxBhiIuk4axoNdWQlqqVShhqd774Ctw&s\" alt=\"img4\">\r\n");
      out.write("                    <img src=\"https://img.freepik.com/free-photo/closeup-shot-beautiful-african-elephant_181624-13558.jpg\" alt=\"img5\">\r\n");
      out.write("                    <img src=\"https://t4.ftcdn.net/jpg/04/59/68/91/360_F_459689140_SF4G5fizLpJhhy8pu93rQk53PL43EwVd.jpg\" alt=\"img6\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS Bundle -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS and jQuery -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
